Question:

**Where is the exception thrown if a coroutine started with async throws an exception?**

<div class="hint">
  Look at the sample code to understand where it is thrown.
</div>

