Question:

**Where is the exception caught if a coroutine started with launch throws an exception?**

<div class="hint">
  Look at the code in the sample. Remove the exception handler and see where the exception is caught.
</div>

