Question:

**Where is a the exception caught if a coroutine started with launch throws an exception?**

<div class="hint">
  The parent of the coroutine. Wrapping the launch call with try catch will catch the exception.
</div>

